name: decora
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_image_overlap: ^0.0.8
  flutter_localizations:
    sdk: flutter
  lottie: 3.0.0
  font_awesome_flutter: ^10.10.0
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.3
  drag_and_drop_lists: ^0.4.2

  camera: ^0.10.0+4
  image_picker: ^0.8.7+4
  object_3d: ^1.0.0

  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1

  email_validator: ^2.1.17
  mailer: ^6.2.4
  http: ^1.5.0
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0
  webview_flutter: ^4.4.4

  provider: ^6.1.2

  flutter_local_notifications: ^17.2.1
  intl: ^0.20.2
  permission_handler: ^11.3.0
  firebase_messaging: ^15.2.1
  googleapis_auth: ^1.6.0
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  

  # Testing packages â€“ MUST be here
  build_runner: ^2.4.9
  mockito: ^5.5.0
  mocktail: ^1.0.4
  bloc_test: ^9.0.5
  firebase_auth_mocks: ^0.14.2
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/DECORA.png"


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - .env

  fonts:
    - family: Montserratt
      fonts:
        - asset: assets/font/Montserrat-Arabic-Light.otf
          weight: 700
